### PR TITLE
Fix padding for right-aligned buttons

### PR DESCRIPTION
**Pull request by KovuTheHusky**
Twitch seems to have updated their player controls and this padding is now unnecessary.

### CODE REVIEW

**Comment by KovuTheHusky** [comment]
Here's a before and after for this change, just to show that the padding is now moving the controls to an incorrect position.

Before

After

**Comment by EchoDev** [comment]
The whisperbutton is still there, you need to be in theather mode to see it overlay the buttons. Twitch maybe didn't update it for everyone yet. Closed for now.

theathermode

**Comment by KovuTheHusky** [comment]
Then I guess it's fine in theater but broken in normal. Does swtiching modes change the dom so you can apply different padding depending on that? Like `#normalPlayer > .player-buttons-right` versus `#theaterPlayer > .player-buttons-right` or something?

**Comment by EchoDev** [comment]
Nope, it stays the same. You prolly could move the buttons after triggering the fullscreen but that would create a lot of unnecessary code for a small cosmetical fix. I can maybe look into it later.

**Comment by KovuTheHusky** [comment]
Mm, probably not worth it as long as Twitch sticks to their roadmap for HTML5. Thanks for the script in the interim.

**Pull request closed without merging**
